global:
  debug: true
  disable_auth: false
server:
  global:
    environment: production
    engine.signals.on: true
    server.socket_host: 0.0.0.0
    server.socket_port: 80
    server.thread_pool: 8
    server.max_request_body_size: 0
    server.socket_timeout: 60
  "/":
    tools.sessions.on: true
    tools.sessions.name: auth_session_id
    tools.sessions.httponly: true
    tools.sessions.secure: false
    tools.proxy.on: true
    tools.proxy.local: Host
    tools.secureheaders.on: true
    tools.staticdir.on: true
    tools.staticdir.dir: static
endpoints:
  root: "/forward-auth/"
  saml: "/forward-auth/saml"
  oidc: "/forward-auth/oidc"
  info: "/forward-auth/info"
  access_denied: "/access_denied"
auth:
  auth_redirect: "${APP_HOST}/forward-auth/login"
  login_handler: "/forward-auth/oidc/login"
  logout_handler: "/forward-auth/oidc/logout"
  login_default_redirect_url: "${APP_HOST}/"
  logout_default_redirect_url: "${APP_HOST}/"
  logout_allowed_redirect_urls:
  - ${APP_HOST}/
mappers:
  header:
    grafana:
      X-WEBAUTH-USER: "'auth_attributes'.'preferred_username'"
      X-WEBAUTH-NAME: "'auth_attributes'.'name'"
      X-WEBAUTH-EMAIL: "'auth_attributes'.'email'"
  json:
    galloper:
      login: "'auth_attributes'.'preferred_username'"
      name: "'auth_attributes'.'name'"
      email: "'auth_attributes'.'email'"
oidc:
  debug: true
  provider:
    configuration:
      issuer: "${APP_HOST}/auth/realms/carrier"
      authorization_endpoint: "${APP_HOST}/auth/realms/carrier/protocol/openid-connect/auth"
      token_endpoint: "http://carrier-keycloak:8080/auth/realms/carrier/protocol/openid-connect/token"
      token_introspection_endpoint: "${APP_HOST}/auth/realms/carrier/protocol/openid-connect/token/introspect"
      userinfo_endpoint: "http://carrier-keycloak:8080/auth/realms/carrier/protocol/openid-connect/userinfo"
      end_session_endpoint: "${APP_HOST}/auth/realms/carrier/protocol/openid-connect/logout"
      jwks_uri: "http://carrier-keycloak:8080/auth/realms/carrier/protocol/openid-connect/certs"
      check_session_iframe: "${APP_HOST}/auth/realms/carrier/protocol/openid-connect/login-status-iframe.html"
      grant_types_supported: ["authorization_code","implicit","refresh_token","password","client_credentials"]
      response_types_supported: ["code","none","id_token","token","id_token token","code id_token","code token","code id_token token"]
      subject_types_supported: ["public","pairwise"]
      id_token_signing_alg_values_supported: ["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512"]
      id_token_encryption_alg_values_supported: ["RSA-OAEP","RSA1_5"]
      id_token_encryption_enc_values_supported: ["A128GCM","A128CBC-HS256"]
      userinfo_signing_alg_values_supported: ["PS384","ES384","RS384","HS256","HS512","ES256","RS256","HS384","ES512","PS256","PS512","RS512","none"]
      request_object_signing_alg_values_supported: ["PS384","ES384","RS384","ES256","RS256","ES512","PS256","PS512","RS512","none"]
      response_modes_supported: ["query","fragment","form_post"]
      registration_endpoint: "${APP_HOST}/auth/realms/carrier/clients-registrations/openid-connect"
      token_endpoint_auth_methods_supported: ["private_key_jwt","client_secret_basic","client_secret_post","tls_client_auth","client_secret_jwt"]
      token_endpoint_auth_signing_alg_values_supported: ["PS384","ES384","RS384","ES256","RS256","ES512","PS256","PS512","RS512"]
      claims_supported: ["aud","sub","iss","auth_time","name","given_name","family_name","preferred_username","email","acr"]
      claim_types_supported: ["normal"]
      claims_parameter_supported: False
      scopes_supported: ["openid","offline_access","profile","email","address","phone","roles","web-origins","microprofile-jwt"]
      request_parameter_supported: True
      request_uri_parameter_supported: True
      code_challenge_methods_supported: ["plain","S256"]
      tls_client_certificate_bound_access_tokens: True
      introspection_endpoint: "${APP_HOST}/auth/realms/carrier/protocol/openid-connect/token/introspect"
    registration:
      client_id: carrier-oidc
      client_secret: ${KEYCLOAK_KEY}
      redirect_uris:
      - "${APP_HOST}/forward-auth/oidc/callback"
      post_logout_redirect_uris:
      - "${APP_HOST}"